### ISSUE TITLE
RNAudioRecorderPlayer.startPlayer got 3 arguments expected 4

### ISSUE THREAD

**Issue by pavelustenko** [dooboolab/react-native-audio-recorder-player#233]
### Version of react-native-audio-recorder-player
2.6.0-rc1

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Play recorded audio 

### Actual behavior
Red screen RNAudioRecorderPlayer.startPlayer got 3 arguments expected 4 in debug, app crash in release

### Steps to reprodue the behabior
get Example project from repo, upgrade react-native-audio-recorder-player to latest, record audio, press play.

**Comment by yogesh-dalvi** [comment]
@pavelustenko  me too stuck over here

**Comment by hyochan** [comment]
Could you try `2.6.0-rc2` and come back? Since I've just quickly updated this, I have not tested this yet. I'll test this in a few hours. Sorry about that. Hope it works. If not please roll back to `2.5.+`.

**Comment by yogesh-dalvi** [comment]
@hyochan not working with `2.6.0-rc2`. Still the same error.

**Comment by niloofarsadeghii76** [comment]
i have same problem too

**Comment by yogesh-dalvi** [comment]
hey @hyochan , I upgraded to `2.5.4` and now it doesn't show the above mentioned error when I play the recorded audio, but why do i continuously get this `Error: mediaPlayer is null.` error in **console** when I play the recorded audio?

**Comment by hyochan** [comment]
Resolved in `2.6.0-rc3`. This is very strange that `Platform.select` API isn't working as expected. You may see https://github.com/dooboolab/react-native-audio-recorder-player/commit/08605869ce4314f240e81c706d8ecb3ae8d7ac2b.

**Comment by hyochan** [comment]
> hey @hyochan , I upgraded to `2.5.4` and now it doesn't show the above mentioned error when I play the recorded audio, but why do i continuously get this `Error: mediaPlayer is null.` error in **console** when I play the recorded audio?

You may ignore that error message. That is shown when you attempt to play for stop player when the operation is already done (meaning you're trying to do something twice).

**Comment by yogesh-dalvi** [comment]
Hey @hyochan , `2.6.0-rc3` is also not working for me still not able to play recorded audio but `2.5.4` works file.  Thank you :)

**Comment by hyochan** [comment]
Strange! I have tested it in example. Let me check tommorow.

**Comment by hyochan** [comment]
> Hey @hyochan , `2.6.0-rc3` is also not working for me still not able to play recorded audio but `2.5.4` works file. Thank you :)

Just tested. This is working fine in my env. Could you confirm that `rc3` has same error as `rc2` and `rc1`?

**Comment by yogesh-dalvi** [comment]
Hey @hyochan  `2.6.0-rc3` this is working, Thanks :)
